version: "3"

vars:
  AGENT_BIN: agent/bin/pulse-agent
  API_BIN: api/bin/pulse-api
  CLI_BIN: cli/bin/pulse
  REGISTRY: git.andcake.dev/ivan
  IMAGE_AGENT: pulse-agent
  IMAGE_API: pulse-api
  IMAGE_UI: pulse-ui

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list


  clean:
    desc: Remove build artifacts
    cmds:
      - rm -f {{.AGENT_BIN}} {{.API_BIN}} {{.CLI_BIN}}
