server {
    listen 3000;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /healthz {
        proxy_pass http://pulse-api:8080;
        proxy_set_header Host $host;
    }

    location /status {
        proxy_pass http://pulse-api:8080;
        proxy_set_header Host $host;
    }

    location /nodes {
        proxy_pass http://pulse-api:8080;
        proxy_set_header Host $host;
    }
}
